# Generated by Django 4.2.4 on 2023-08-10 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_remove_customer_last_login_customer_last_login_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='last_login_time',
        ),
        migrations.AddField(
            model_name='customer',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
