# Generated by Django 4.0 on 2022-02-06 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyproduct', '0002_buyproduct_product_qty_buyproduct_tot_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyproduct',
            name='esewa_id',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='buyproduct',
            name='location',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='buyproduct',
            name='pin',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
