# Generated by Django 4.0 on 2022-02-07 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyproduct', '0004_buyproduct_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyproduct',
            name='contact_no',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
