# Generated by Django 4.2.4 on 2023-08-11 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyproduct', '0005_buyproduct_contact_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyproduct',
            name='esewa_id',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='buyproduct',
            name='pin',
            field=models.CharField(max_length=128),
        ),
    ]
